# Generated by Django 5.1 on 2024-08-23 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_category_comments_listings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bids',
            new_name='Bid',
        ),
        migrations.RenameModel(
            old_name='comments',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='Listings',
            new_name='Listing',
        ),
    ]
