# Generated by Django 5.1 on 2024-09-09 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_listing_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commented_listing', to='auctions.listing'),
        ),
        migrations.AddField(
            model_name='comment',
            name='message',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image_url',
            field=models.URLField(blank=True, default='no url', max_length=1000),
        ),
    ]
